export const STATS = [
"Goals",
"Assists",
"Non-Penalty Goals",
"Penalty Kicks Made",
"Penalty Kicks Attempted",
"Yellow Cards",
"Red Cards",
"xG",
"xA",
"npxG+xA",
"Shots Total",
"Shots on target",
"Shots on target %",
"Goals/Shot",
"Goals/Shot on target",
"Average Shot Distance",
"Shots from free kicks",
"npxG",
"npxG/Sh",
"Goals - xG",
"Non-Penalty Goals - npxG",
"Passes Completed",
"Passes Attempted",
"Pass Completion %",
"Total Passing Distance",
"Progressive Passing Distance",
"Passes Completed (Short)",
"Passes Attempted (Short)",
"Pass Completion % (Short)",
"Passes Completed (Medium)",
"Passes Attempted (Medium)",
"Pass Completion % (Medium)",
"Passes Completed (Long)",
"Passes Attempted (Long)",
"Pass Completion % (Long)",
"xA",
"Key Passes",
"Passes into Final Third",
"Passes into Penalty Area",
"Crosses into Penalty Area",
"Progressive Passes",
"Passes Attempted",
"Live-ball passes",
"Dead-ball passes",
"Passes from Free Kicks",
"Through Balls",
"Passes Under Pressure",
"Switches",
"Crosses",
"Corner Kicks",
"Inswinging Corner Kicks",
"Outswinging Corner Kicks",
"Straight Corner Kicks",
"Ground passes",
"Low Passes",
"High Passes",
"Passes Attempted (Left)",
"Passes Attempted (Right)",
"Passes Attempted (Head)",
"Throw-Ins taken",
"Passes Attempted (Other)",
"Passes Completed",
"Passes Offside",
"Passes Out of Bounds",
"Passes Intercepted",
"Passes Blocked",
"Shot-Creating Actions",
"SCA (PassLive)",
"SCA (PassDead)",
"SCA (Drib)",
"SCA (Sh)",
"SCA (Fld)",
"SCA (Def)",
"Goal-Creating Actions",
"GCA (PassLive)",
"GCA (PassDead)",
"GCA (Drib)",
"GCA (Sh)",
"GCA (Fld)",
"GCA (Def)",
"Tackles",
"Tackles Won",
"Tackles (Def 3rd)",
"Tackles (Mid 3rd)",
"Tackles (Att 3rd)",
"Dribblers Tackled",
"Dribbles Contested",
"% of dribblers tackled",
"Dribbled Past",
"Pressures",
"Successful Pressures",
"Successful Pressure %",
"Pressures (Def 3rd)",
"Pressures (Mid 3rd)",
"Pressures (Att 3rd)",
"Blocks",
"Shots Blocked",
"Shots Saved",
"Passes Blocked",
"Interceptions",
"Tkl+Int",
"Clearances",
"Errors",
"Touches",
"Touches (Def Pen)",
"Touches (Def 3rd)",
"Touches (Mid 3rd)",
"Touches (Att 3rd)",
"Touches (Att Pen)",
"Touches (Live-Ball)",
"Dribbles Completed",
"Dribbles Attempted",
"Successful Dribble %",
"Players Dribbled Past",
"Nutmegs",
"Carries",
"Total Carrying Distance",
"Progressive Carrying Distance",
"Progressive Carries",
"Carries into Final Third",
"Carries into Penalty Area",
"Miscontrols",
"Dispossessed",
"Pass Targets",
"Passes Received",
"Passes Received %",
"Progressive Passes Rec",
"Red Cards",
"Second Yellow Card",
"Fouls Committed",
"Fouls Drawn",
"Offsides",
"Crosses",
"Interceptions",
"Tackles Won",
"Penalty Kicks Won",
"Penalty Kicks Conceded",
"Own Goals",
"Ball Recoveries",
"Aerials won",
"Aerials lost",
"% of Aerials Won"
]